## 1. Database & Schema Setup

```sql
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE DEA_REAL_TIME_SCD1;
USE DATABASE DEA_REAL_TIME_SCD1;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA TRANSFORMED;
```
